version: '3.8'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'didactec.com.co -> http://socket_server:3003'
      STAGE: 'production'
      WEBSOCKET: 'true'  # IMPORTANTE: Habilitar WebSockets en el proxy
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - socket_server  # Reemplaza 'links' por 'depends_on'

  socket_server:
    build: .
    ports:
      - "3003:3003"
    container_name: socket_server
    working_dir: /usr/src/app
    command: >
      /bin/sh -c "npm install && npm start"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Evita conflictos con node_modules
    restart: always
    environment:
      - NODE_ENV=production

volumes:
  https-portal-data:
